; CouchDB config tuned for Obsidian Self-hosted LiveSync

[httpd]
enable_cors = true

[cors]
credentials = true
headers = accept, authorization, content-type, origin, referer
methods = GET, PUT, POST, HEAD, DELETE
origins = *

[chttpd]
require_valid_user = false
max_http_request_size = 4294967296
bind_address = 0.0.0.0

[couchdb]
max_document_size = 50000000
